# Generated by Django 5.0.4 on 2026-05-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(blank=True, max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(default='Bachelor', max_length=50)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('tuition_fee_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faculties',
                'ordering': ['university', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_universities',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_uz', models.CharField(blank=True, max_length=300)),
                ('name_ru', models.CharField(blank=True, max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(choices=[('UZ', 'Uzbekistan'), ('US', 'United States'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('RU', 'Russia'), ('KR', 'South Korea'), ('TR', 'Turkey'), ('CN', 'China'), ('JP', 'Japan'), ('MY', 'Malaysia'), ('OT', 'Other')], max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('tuition_fee_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_fee_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('has_scholarships', models.BooleanField(default=False)),
                ('scholarship_info', models.TextField(blank=True)),
                ('scholarship_coverage', models.CharField(blank=True, max_length=200)),
                ('required_ielts', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('required_sat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('required_toefl', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('required_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('dtm_passing_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('world_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('national_ranking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qs_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('the_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('application_deadline_fall', models.DateField(blank=True, null=True)),
                ('application_deadline_spring', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='universities/covers/')),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('international_students', models.PositiveIntegerField(blank=True, null=True)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'db_table': 'universities',
                'ordering': ['world_ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'university_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
