# Generated by Django 5.0.4 on 2026-05-16 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saveduniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_universities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['country'], name='universitie_country_bf4017_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['world_ranking'], name='universitie_world_r_0185ca_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['is_active', 'is_featured'], name='universitie_is_acti_62794e_idx'),
        ),
        migrations.AddField(
            model_name='saveduniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university'),
        ),
        migrations.AddField(
            model_name='universityreview',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='universities.university'),
        ),
        migrations.AddField(
            model_name='universityreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='saveduniversity',
            unique_together={('user', 'university')},
        ),
        migrations.AlterUniqueTogether(
            name='universityreview',
            unique_together={('user', 'university')},
        ),
    ]
