# Generated by Django 5.0.4 on 2026-05-16 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar/Tuman')),
                ('school', models.CharField(blank=True, max_length=200, null=True, verbose_name='Maktab')),
                ('grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sinf')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('study_language', models.CharField(blank=True, max_length=50, null=True)),
                ('study_goal', models.CharField(blank=True, choices=[('uzbekistan', "O'zbekistonda o'qish"), ('abroad', "Chet elda o'qish"), ('both', 'Ikkalasi ham')], max_length=20, null=True)),
                ('dream_university', models.CharField(blank=True, max_length=200, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('exam_subjects', models.JSONField(blank=True, default=list)),
                ('dtm_subjects', models.JSONField(blank=True, default=list)),
                ('dtm_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='DTM ball')),
                ('nat_cert_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Milliy sertifikat ball')),
                ('ielts_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sat_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toefl_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('other_cert', models.CharField(blank=True, max_length=200, null=True)),
                ('other_cert_score', models.CharField(blank=True, max_length=50, null=True)),
                ('target_score', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('banned', 'Bloklangan'), ('inactive', 'Nofaol')], default='active', max_length=20)),
                ('is_subscribed_to_channels', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('xp_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('study_streak', models.PositiveIntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('remind_study', models.BooleanField(default=True)),
                ('remind_time', models.TimeField(blank=True, null=True)),
                ('remind_exam', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('onboarding_done', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banned_users',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('target_audience', models.CharField(choices=[('all', 'Hammaga'), ('premium', 'Premium'), ('free', 'Bepul'), ('active', 'Faol (7 kun)')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirilgan'), ('running', 'Yuborilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Xato')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='users_telegra_d76140_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_status_9ca66f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_premium'], name='users_is_prem_41b83a_idx'),
        ),
    ]
