# Generated by Django 6.0.5 on 2026-05-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
