"""Har bir fanga 50+ savol qo'shish."""
import os, sys, django
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.local')
os.environ.setdefault('USE_SQLITE', 'true')
django.setup()

from apps.education.models import Subject, Question

ALL_QUESTIONS = {
    'math': [
        ("2x+6=14, x=?","3","4","5","6","B","2x=8, x=4","easy"),
        ("3x-9=0, x=?","1","2","3","4","C","3x=9","easy"),
        ("x²-9=0, x=?","±2","±3","±4","±9","B","x²=9","easy"),
        ("log₂(64)=?","4","5","6","8","C","2⁶=64","medium"),
        ("log₁₀(1000)=?","2","3","4","10","B","10³=1000","easy"),
        ("2ˣ=32, x=?","4","5","6","8","B","2⁵=32","easy"),
        ("5²+12²=?","144","169","196","225","B","25+144=169","easy"),
        ("√169=?","11","12","13","14","C","13²=169","easy"),
        ("(x+3)(x-3)=?","x²-6","x²-9","x²+9","x²-3","B","(a+b)(a-b)=a²-b²","medium"),
        ("|-15|=?","-15","0","15","150","C","absolut qiymat musbat","easy"),
        ("3!=?","3","6","9","12","B","3×2×1=6","easy"),
        ("f(x)=x²+1, f(3)=?","8","9","10","11","C","9+1=10","easy"),
        ("f(x)=2x-3, f(0)=?","-3","-2","0","3","A","2×0-3=-3","easy"),
        ("4x=20, x=?","4","5","6","8","B","20/4=5","easy"),
        ("15% of 300=?","35","40","45","50","C","300×0.15=45","easy"),
        ("1+2+3+...+20=?","180","190","200","210","D","n(n+1)/2=210","medium"),
        ("cos(60°)=?","0","1/2","√3/2","1","B","cos(60°)=1/2","easy"),
        ("tan(45°)=?","0","1/2","1","√3","C","tan(45°)=1","easy"),
        ("sin²x+cos²x=?","0","1/2","1","2","C","asosiy identiklik","easy"),
        ("Doira yuzi r=10 (π≈3.14)=?","31.4","62.8","314","628","C","πr²=314","medium"),
        ("Kub hajmi a=4=?","16","32","64","128","C","4³=64","easy"),
        ("To'g'ri to'rtburchak P a=6,b=4=?","20","22","24","26","A","2(6+4)=20","easy"),
        ("(2+3)²=?","10","20","25","30","C","5²=25","easy"),
        ("2⁸=?","128","256","512","1024","B","2⁸=256","medium"),
        ("0.5³=?","0.025","0.125","0.25","0.5","B","0.5×0.5×0.5=0.125","medium"),
        ("Agar x+y=10, x-y=4 bo'lsa x=?","5","6","7","8","C","2x=14, x=7","medium"),
        ("3x²=75, x=?","±3","±4","±5","±6","C","x²=25, x=±5","medium"),
        ("log₃(81)=?","2","3","4","5","C","3⁴=81","medium"),
        ("(a-b)²=?","a²-b²","a²-2ab+b²","a²+2ab+b²","a²-ab","B","kvadrat ayirma","medium"),
        ("n ta toq son yig'indisi=?","n","n²","n(n+1)","2n","B","1+3+5+...=n²","hard"),
        ("Progressiya: 2,4,8,16... keyingi=?","24","32","36","64","B","×2 ko'paytma","easy"),
        ("Progressiya: 3,6,9,12... keyingi=?","14","15","16","18","B","+3 arifmetik","easy"),
        ("x/4=5, x=?","10","15","20","25","C","x=20","easy"),
        ("2x-3=7, x=?","4","5","6","7","B","2x=10, x=5","easy"),
        ("Agar 2^(x+1)=16 bo'lsa x=?","2","3","4","5","B","2^(x+1)=2⁴, x+1=4","medium"),
        ("√(16+9)=?","4","5","6","7","B","√25=5","easy"),
        ("125^(1/3)=?","3","4","5","6","C","5³=125","medium"),
        ("Agar ab=12 va a+b=7 bo'lsa a²+b²=?","25","36","49","61","A","(a+b)²-2ab=49-24=25","hard"),
        ("i²=? (kompleks son)","1","i","-1","0","C","i²=-1 ta'rif","hard"),
        ("Agar x=3 bo'lsa 2x²-3x+1=?","8","9","10","11","C","18-9+1=10","medium"),
        ("sin(0°)=?","0","1/2","1","√3/2","A","sin(0)=0","easy"),
        ("cos(90°)=?","0","1/2","1","-1","A","cos(90°)=0","easy"),
        ("Uchburchak yuzasi a=6, h=4=?","10","12","14","16","B","S=ah/2=12","easy"),
        ("Trapetsiya yuzasi a=5,b=3,h=4=?","14","16","18","20","B","S=(a+b)h/2=16","medium"),
        ("2⁰=?","0","1","2","4","B","istalgan son⁰=1","easy"),
        ("(-3)²=?","-9","3","6","9","D","(-3)²=9","easy"),
        ("√2 ≈?","1.14","1.41","1.44","1.73","B","√2≈1.414","medium"),
        ("π ≈?","3.12","3.14","3.16","3.18","B","π≈3.14159","easy"),
        ("e ≈?","2.52","2.62","2.72","2.82","C","e≈2.718","hard"),
        ("Kombinatsiya C(5,2)=?","5","10","15","20","B","5!/(2!3!)=10","hard"),
        ("Permutatsiya P(4,2)=?","6","8","10","12","D","4×3=12","hard"),
    ],
    'english': [
        ("'Beautiful' sinonimi:","Ugly","Pretty","Bad","Small","B","Pretty=beautiful","easy"),
        ("'Fast' antonimi:","Quick","Slow","Run","Speed","B","Fast≠Slow","easy"),
        ("She ___ to school every day.","go","goes","going","gone","B","She+goes (3-shaxs)","easy"),
        ("They ___ football yesterday.","play","played","playing","plays","B","yesterday=past","easy"),
        ("I ___ TV when you called.","watched","watch","was watching","am watching","C","past continuous","medium"),
        ("By 2030 they ___ the project.","finish","finished","will finish","will have finished","D","future perfect","hard"),
        ("The book ___ by Tolstoy.","wrote","written","was written","has written","C","passive voice","medium"),
        ("If I ___ rich, I would travel.","am","was","were","will be","C","2nd conditional","medium"),
        ("She asked me where I ___ from.","come","came","comes","coming","B","indirect question","hard"),
        ("'Abandon' ma'nosi:","Find","Keep","Leave","Start","C","abandon=tark etish","medium"),
        ("'Enormous' ma'nosi:","Tiny","Huge","Normal","Strange","B","enormous=huge","easy"),
        ("'Pristine' ma'nosi:","Dirty","Old","Perfect/Clean","Broken","C","pristine=mukammal","medium"),
        ("Past tense of 'buy':","buyed","boughted","bought","buys","C","irregular verb","easy"),
        ("Plural of 'child':","childs","childes","children","child's","C","irregular plural","easy"),
        ("Superlative of 'good':","gooder","better","goodest","best","D","irregular: best","easy"),
        ("'Although' qanday bog'lovchi?","Reason","Result","Contrast","Addition","C","contrast conjunction","medium"),
        ("I wish I ___ speak French.","can","could","will","would","B","wish+could","medium"),
        ("Neither A nor B ___ correct.","are","is","were","be","B","neither...nor+singular","hard"),
        ("'Investigate' ma'nosi:","Ignore","Examine","Destroy","Build","B","investigate=tekshirish","medium"),
        ("He's been working here ___ 5 years.","since","for","ago","during","B","for=davomiylik","easy"),
        ("'Ambiguous' ma'nosi:","Clear","Certain","Double meaning","Simple","C","ikki ma'noli","medium"),
        ("The report ___ by Monday.","will review","will be reviewed","reviews","reviewing","B","future passive","medium"),
        ("'Inevitably' ma'nosi:","Rarely","Possibly","Certainly","Slowly","C","inevitably=albatta","hard"),
        ("'Procrastinate' ma'nosi:","Hurry","Delay","Plan","Complete","B","kechiktirish","hard"),
        ("'Meticulous' ma'nosi:","Careless","Very careful","Quick","Lazy","B","juda ehtiyotkor","hard"),
        ("I ___ here since 2020.","live","lived","have lived","am living","C","present perfect+since","medium"),
        ("'Despite' qanday ishlatiladi?","Despite+ing","Despite+that","Despite+noun/ing","Despite+to","C","despite+noun/gerund","hard"),
        ("'Used to' nimani bildiradi?","Present habit","Past habit","Future plan","Current state","B","o'tgan odat","medium"),
        ("'Passive voice' yasash:","Subject+verb","Subject+be+V3","Object+verb","Be+subject","B","be+past participle","medium"),
        ("'Hardly' ma'nosi:","Easily","Almost never","Very hard","Quickly","B","deyarli hech qachon","medium"),
        ("Correct: He ___ home now.","go","goes","is going","gone","C","present continuous","easy"),
        ("'Vocabulary' ma'nosi:","Grammar","Words","Pronunciation","Spelling","B","so'z boyligi","easy"),
        ("'Fluent' ma'nosi:","Broken","Smooth/Easy","Hard","Slow","B","ravon","easy"),
        ("'Efficient' ma'nosi:","Wasteful","Effective","Slow","Careless","B","samarali","medium"),
        ("'Collaborate' ma'nosi:","Compete","Work together","Disagree","Separate","B","hamkorlik qilish","medium"),
        ("The ___ (pretty) girl smiled.","more pretty","prettiest","most prettier","prettier","B","comparative adj","medium"),
        ("'Scarce' ma'nosi:","Plentiful","Rare/Limited","Common","Many","B","kam/cheklangan","hard"),
        ("'Consecutive' ma'nosi:","Random","Following in order","Mixed","Separate","B","ketma-ket","hard"),
        ("'Elaborate' ma'nosi:","Simple","Detailed","Quick","Vague","B","batafsil","hard"),
        ("'Perseverance' ma'nosi:","Giving up","Persistence","Laziness","Doubt","B","qat'iyat","hard"),
        ("Preposition: She is good ___ math.","in","at","on","for","B","good at=yaxshi","easy"),
        ("Preposition: I arrived ___ Monday.","in","at","on","by","C","on+weekday","easy"),
        ("Preposition: He lives ___ London.","at","in","on","by","B","in+city","easy"),
        ("'Regardless' ma'nosi:","Because of","In spite of","Due to","As a result","B","qaramay","hard"),
        ("'Reluctant' ma'nosi:","Eager","Unwilling","Happy","Excited","B","ishtiyaqsiz","hard"),
        ("'Subsequent' ma'nosi:","Previous","Following","Current","Initial","B","keyingi","hard"),
        ("Article: ___ sun is hot.","A","An","The","No article","C","unique thing=the","easy"),
        ("Article: She is ___ engineer.","a","an","the","no","B","vowel sound=an","easy"),
        ("'Phenomenon' ko'pligi:","Phenomenons","Phenomena","Phenomenas","Phenomenes","B","Greek plural","hard"),
        ("'Criterion' ko'pligi:","Criterions","Criterias","Criteria","Criterions","C","Greek plural","hard"),
    ],
    'physics': [
        ("F=ma — bu qaysi qonun?","1-qonun","2-qonun","3-qonun","Energiya","B","Nyuton 2-qonuni","easy"),
        ("g=? m/s²","8.9","9.8","10.8","11","B","g≈9.8 m/s²","easy"),
        ("Yorug'lik tezligi=?","3×10⁶","3×10⁸","3×10¹⁰","3×10⁴","B","c=3×10⁸ m/s","easy"),
        ("Ohm qonuni I=?","R/U","U×R","U/R","R-U","C","I=U/R","easy"),
        ("Quvvat P=?","I/U","U/I","U×I","U+I","C","P=UI","easy"),
        ("Kinetik energiya Ek=?","mv","mv²","mv²/2","2mv²","C","Ek=mv²/2","medium"),
        ("Potensial energiya Ep=?","mgh","mg/h","m+g+h","mh/g","A","Ep=mgh","easy"),
        ("1 Joule=?","1N×m","1kg×m","1W×s²","1N/m","A","J=N×m","medium"),
        ("Boyle qonuni P₁V₁=P₂V₂ (T=const) bu:","Izobarik","Izotermik","Izoxorik","Adiabatik","B","T=const=izotermik","hard"),
        ("Issiqlik Q=?","mcT","mc/T","m+c","c/mT","A","Q=mcΔT","medium"),
        ("Absolut nol=?","0°C","-100°C","-273°C","-373°C","C","0 Kelvin=-273°C","medium"),
        ("Elektr zaryad birligi:","Amper","Volt","Kulon","Om","C","Kulon (C)","easy"),
        ("Inersiya nima?","Tezlanish","Harakat saqlanishi","Kuch","Energiya","B","jism holatini saqlash","medium"),
        ("Nyuton 3-qonuni:","F=ma","Har kuchga teng qarama-qarshi kuch","Inersiya","Energiya","B","harakat-reaksiya","easy"),
        ("Mexanik ish A=?","F×t","F/s","F×s","F+s","C","A=F×s","easy"),
        ("Quvvat N=?","A×t","A/t","A+t","F×t","B","N=A/t","medium"),
        ("1 kVt=?","100 Vt","1000 Vt","10 Vt","10000 Vt","B","kilo=1000","easy"),
        ("Temperatura birligi SI=?","Celsius","Fahrenheit","Kelvin","Rankine","C","SI=Kelvin","medium"),
        ("Elektr qarshilik birligi=?","Amper","Volt","Kulon","Om","D","Om (Ω)","easy"),
        ("Kuchlanish birligi=?","Amper","Volt","Kulon","Om","B","Volt (V)","easy"),
        ("Parallel ulanganda umumiy qarshilik:","Ortadi","Kamayadi","O'zgarmaydi","Nolga teng","B","parallel=kam qarshilik","medium"),
        ("Ketma-ket ulanganda umumiy qarshilik:","Ortadi","Kamayadi","O'zgarmaydi","Nolga teng","A","ketma-ket=qo'shiladi","easy"),
        ("Magnit induksiya birligi=?","Tesla","Gauss","Veber","Henri","A","Tesla (T)","hard"),
        ("Yorug'likning to'lqin uzunligi ko'rinadigan=?","1-10 nm","400-700 nm","1-10 mm","1-10 m","B","ko'rinadigan spektr","medium"),
        ("Atom yadrosi nimadan iborat?","Proton","Proton va Neytron","Elektron","Proton va Elektron","B","yadro tarkibi","easy"),
        ("Elektron zaryadi=?","Musbat","Nol","Manfiy","O'zgaruvchan","C","elektron manfiy","easy"),
        ("Proton zaryadi=?","Manfiy","Nol","Musbat","O'zgaruvchan","C","proton musbat","easy"),
        ("Alfa zarracha nima?","Geliy yadrosi","Elektron","Foton","Neytron","A","2p+2n=He yadro","hard"),
        ("Nur sindirish indeksi n=?","c/v","v/c","c×v","c+v","A","n=c/v","hard"),
        ("Guk qonuni F=?","kx","k/x","k+x","kx²","A","F=kx (elastiklik)","medium"),
        ("Mayatnik davri T=?","2π√(l/g)","2π√(g/l)","πl/g","2πlg","A","T=2π√(l/g)","hard"),
        ("Rezonans nima?","Tebranish to'xtashi","Amplituda maksimum","Davr nol","Tezlik max","B","tashqi chastota=tabiiy","hard"),
        ("1 atm=? Pa","101325","10000","1000","100","A","1 atm=101325 Pa","hard"),
        ("Issiqlik o'tkazuvchanlik=?","Suyuqlik oqimi","Molekulalar orqali","Nur chiqarish","Konveksiya","B","temas orqali","medium"),
        ("Konveksiya nima?","Temas orqali","Suyuqlik/gaz oqimi","Nur orqali","Molekulalar","B","oqim orqali issiqlik","medium"),
        ("Termodinamika 1-qonuni:","Q=A","ΔU=Q-A","Q=ΔU","A=ΔU+Q","B","ichki energiya","hard"),
        ("Bernulli tenglamasi qaysi sohada?","Elektr","Gidrodinamika","Optika","Atom fizika","B","suyuqlik harakati","hard"),
        ("Arximed kuchi F=?","ρgV","mg","ρV","gV","A","F=ρgV","medium"),
        ("Pascal qonuni nima?","Qattiq jism","Suyuqlik bosimi","Gaz qonuni","Nur","B","suyuqlikda bosim","medium"),
        ("Doppler effekti nima?","Rang o'zgarish","Chastota o'zgarishi harakatda","Amplituda","Tezlik","B","manba harakatida","hard"),
        ("Foton energiyasi E=?","hf","hc","mc²","h/f","A","E=hf (Plank)","hard"),
        ("Rentgen nurlari to'lqin uzunligi:","400-700nm","0.01-10nm","1-100mm","1-10m","B","qisqa to'lqin","hard"),
        ("Lazer nima?","Oddiy yorug'lik","Kogerent yorug'lik","Qizil nur","Rentgen","B","kogerent=bir fazali","hard"),
        ("1 eV=? J","1.6×10⁻¹⁹","1.6×10⁻¹⁶","9.1×10⁻³¹","6.6×10⁻³⁴","A","elektron-volt","hard"),
        ("Plank konstantasi h≈?","6.63×10⁻³⁴","6.63×10⁻³¹","9.1×10⁻³¹","1.6×10⁻¹⁹","A","h=6.63×10⁻³⁴ J×s","hard"),
        ("Avogadro soni≈?","6.02×10²³","6.02×10²⁰","6.02×10²⁶","3.01×10²³","A","NA=6.022×10²³","hard"),
        ("Gaz konstantasi R≈?","8.31 J/(mol×K)","0.831","83.1","831","A","R=8.314","hard"),
        ("Bolsman konstantasi k≈?","1.38×10⁻²³","1.38×10⁻¹⁹","1.38×10⁻³¹","1.38×10²³","A","k=1.38×10⁻²³","hard"),
        ("Yadro reaksiyasida qanday energiya ajraladi?","Kimyoviy","Issiqlik","Yadro","Mexanik","C","E=mc²","hard"),
        ("Yarimo'tkazgich misoli:","Mis","Kremniy","Oltin","Kumush","B","Si — yarimo'tkazgich","medium"),
        ("p-n o'tish nima?","Rezistor","Diod asosi","Kondensator","Transformator","B","yarimo'tkazgich junction","hard"),
    ],
    'chemistry': [
        ("H₂O formulasi:","Tuz","Suv","Spirt","Kislorod","B","suv formulasi","easy"),
        ("NaCl nima?","Soda","Osh tuzi","Sirka","Shakar","B","natriy xlorid","easy"),
        ("CO₂ nima?","Kislorod","Azot","Karbonat angidrid","Vodorod","C","karbon dioksid","easy"),
        ("pH=7 nima bildiradi?","Kislotali","Neytral","Ishqoriy","Tuzli","B","neytral muhit","easy"),
        ("pH<7 nima?","Ishqoriy","Neytral","Kislotali","Tuzli","C","kislotali muhit","easy"),
        ("pH>7 nima?","Kislotali","Neytral","Ishqoriy","Tuzli","C","ishqoriy muhit","easy"),
        ("Eng yengil element:","Geliy","Litiy","Vodorod","Neon","C","H, massa=1","easy"),
        ("Valentlik nima?","Atomlar soni","Bog' hosil qilish","Massa","Zaryad","B","kimyoviy bog' soni","medium"),
        ("Oksidlanish=?","Elektron qo'shish","Elektron berish","Proton","Neytron","B","e⁻ yo'qotish","medium"),
        ("Qaytarilish=?","Elektron berish","Elektron olish","Proton berish","Atom","B","e⁻ qabul qilish","medium"),
        ("H₂SO₄ nima?","Xlorid","Sulfat kislota","Nitrat","Fosfor","B","sulfat kislota","easy"),
        ("HCl nima?","Sulfat kislota","Xlorid kislota","Nitrat kislota","Sirka","B","xlorid kislota","easy"),
        ("HNO₃ nima?","Sulfat","Xlorid","Nitrat kislota","Fosfor","C","nitrat kislota","easy"),
        ("NaOH nima?","Kislota","Tuz","Ishqor","Oksid","C","natriy gidroksid","easy"),
        ("Ca(OH)₂ nima?","Kislota","Ohak suvi (ishqor)","Tuz","Oksid","B","kaltsiy gidroksid","medium"),
        ("Na₂CO₃ nima?","Osh tuzi","Soda","Kreda","Alum","B","natriy karbonat","medium"),
        ("CaCO₃ nima?","Osh tuzi","Soda","Ohaktosh (kreda)","Alum","C","kaltsiy karbonat","easy"),
        ("Kislota+Ishqor=?","Gaz","Tuz","Tuz+Suv","Oksid","C","neytrallanish","easy"),
        ("Organik kimyo nimani o'rganadi?","Metallar","C birikmalar","Tuzlar","Gazlar","B","uglerod birikmalar","easy"),
        ("Metan formulasi:","CH₄","C₂H₆","C₃H₈","C₂H₄","A","eng oddiy alkan","easy"),
        ("Etanol formulasi:","CH₃OH","C₂H₅OH","C₃H₇OH","HCOOH","B","etil spirti","medium"),
        ("Benzol formulasi:","C₆H₁₂","C₆H₆","C₆H₁₄","C₅H₁₀","B","aromatik birikma","medium"),
        ("Polimer nima?","Oddiy molekula","Uzun zanjir","Ion","Atom","B","monomerlar zanjiri","medium"),
        ("Elektroliz nima?","Issiqlik","Elektr toki bilan","Yorug'lik","Mexanik","B","elektr orqali","medium"),
        ("Avogadro soni≈?","6.02×10²³","6.02×10²⁰","3.01×10²³","12×10²³","A","mol ta'rifi","hard"),
        ("1 mol nima?","100 zarracha","6.02×10²³ zarracha","1000 zarracha","10²⁰ zarracha","B","Avogadro soni","hard"),
        ("Molyar massa birligi:","g","g/mol","mol","kg","B","g/mol","medium"),
        ("Fe₂O₃ nima?","Temir sulfat","Temir(III) oksid","Temir xlorid","Temir nitrat","B","zang","medium"),
        ("Al₂O₃ nima?","Alyuminiy sulfat","Alyuminiy oksid","Korund","B va C","D","Al₂O₃=korund=alyuminiy oksid","medium"),
        ("H₂ + O₂ → ?","H₂O","CO₂","SO₂","NO₂","A","vodorod yonishi","easy"),
        ("C + O₂ → ?","CO","CO₂","CH₄","C₂H₂","B","uglerod yonishi","easy"),
        ("Kislota indikatori: litmus?","Ko'k","Sariq","Qizil","Yashil","C","kislotada qizil","easy"),
        ("Ishqor indikatori: litmus?","Qizil","Ko'k","Sariq","Rangsiz","B","ishqorda ko'k","easy"),
        ("Fenolftalein kislotada:","Qizil","Binafsha","Rangsiz","Sariq","C","kislotada rangsiz","medium"),
        ("Fenolftalein ishqorda:","Rangsiz","Sariq","Binafsha","Qizil","C","ishqorda binafsha","medium"),
        ("Ozon formulasi:","O₂","O₃","O₄","O","B","ozon=O₃","easy"),
        ("NH₃ nima?","Azot oksid","Ammiak","Ammoniy","Nitrat","B","ammiak gazi","easy"),
        ("Uglerod allotroplari:","Olmos va grafit","Olmos va kremniy","Grafit va kvarts","Barchasi","A","C allotroplari","medium"),
        ("Kimyoviy muvozanat qachon?","Reaksiya tugaganda","To'g'ri va teskari tezlik teng","Faqat mahsulot hosil","Reaktantlar tugaganda","B","dinamik muvozanat","hard"),
        ("Le-Shatel'e prinsipi:","Muvozanat siljimaydi","Tashqi ta'sir muvozanatni siljitadi","Reaksiya tezligi","Temperatura","B","muvozanat siljishi","hard"),
        ("Kataliz nima?","Reaksiyani sekinlashtirish","Katalizator bilan tezlashtirish","To'xtatish","O'zgartirish","B","katalizator roli","medium"),
        ("Ferment nima?","Sintetik kataliz","Biologik kataliz","Metal","Vitamin","B","biologik katalizator","hard"),
        ("Izomerlar nima?","Bir xil formula,bir xil tuzilma","Bir xil formula,har xil tuzilma","Har xil formula","Bir xil tuzilma","B","izomeriya","hard"),
        ("Enantiomerlar nima?","Bir xil","Ko'zgu tasvir izomerlar","Zanjir izomeri","Pozitsion izomer","B","optik izomeriya","hard"),
        ("Polimerizatsiya nima?","Parchalanish","Monomerlardan polimer","Oksidlanish","Gidroliz","B","polimer sintezi","medium"),
        ("Gidroliz nima?","Su bilan reaksiya","Kislota bilan","Ishqor bilan","Issiqlik bilan","A","suv bilan parchalanish","medium"),
        ("Esterifikatsiya:","Kislota+Suv","Spirt+Kislota→Ester","Spirt+Ishqor","Base+Suv","B","ester hosil qilish","hard"),
        ("Saponifikatsiya:","Yog'+Suv→Sovun","Spirt+Kislota","Oksidlanish","Qaytarilish","A","sovun ishlab chiqarish","hard"),
        ("Titan (Ti) xossasi:","Yengil va mustahkam","Og'ir va yumshoq","Zaif","Oksidlanuvchi","A","aviatsiyada ishlatiladi","hard"),
        ("Karbid nima?","C+Metal birikma","C+O","C+H","C+N","A","metallarning uglerod birikmasi","hard"),
        ("Nitrid nima?","N+Metal birikma","N+O","N+H","N+C","A","azot birikmasi","hard"),
    ],
    'biology': [
        ("DNK=?","Dezoksiribonuklein kislota","Ribonuklein kislota","Aminokislota","Glyukoza","A","irsiyat moddasi","easy"),
        ("RNK=?","Dezoksiribonuklein","Ribonuklein kislota","Aminokislota","Lipid","B","RNK ta'rifi","easy"),
        ("Mitoxondriya=?","Yadro","Hujayra batareyasi","Ribosoma","Lizosoma","B","ATP ishlab chiqaradi","easy"),
        ("Fotosintez joyi:","Mitoxondriya","Yadro","Xloroplast","Ribosoma","C","xlorofill bor","easy"),
        ("Oqsil sintezi joyi:","Yadro","Xloroplast","Ribosoma","Mitoxondriya","C","mRNA asosida","easy"),
        ("Hujayra devori bor:","Hayvon hujayra","O'simlik hujayra","Bakteriya","B va C","D","o'simlik+bakteriya","medium"),
        ("Mitoz natijasi:","2 diploid","4 haploid","2 haploid","4 diploid","A","bir xil 2 ta","easy"),
        ("Meyoz natijasi:","2 diploid","4 haploid","2 haploid","4 diploid","B","jinsiy hujayralar","medium"),
        ("Xromosomalar soni (inson):","23","46","48","44","B","23 juft=46","easy"),
        ("Qon guruhlari soni:","2","3","4","5","C","I,II,III,IV","easy"),
        ("Evoluysiya muallifi:","Mendel","Darvin","Pasteur","Flemming","B","1859 yil","easy"),
        ("Fotosintez formulasi:","CO₂+H₂O→C₆H₁₂O₆+O₂","O₂+H₂O→CO₂","C₆H₁₂O₆→CO₂","H₂O→H₂+O","A","fotosintez","medium"),
        ("Insulin qayerda?","Jigar","Me'da osti bezi","Buyrak usti","Qalqonsimon","B","Langergans orolchalari","medium"),
        ("En katta organ:","Jigar","Teri","O'pka","Miya","B","~1.5-2 m²","easy"),
        ("ATP nima?","Yog'","Oqsil","Energiya molekulasi","DNK","C","adenozin trifosfat","easy"),
        ("Virus tirikmi?","Ha","Yo'q","Ba'zan","Faqat hayvonda","B","hujayrasiz","medium"),
        ("Bakteriya hujayra turi:","Eukaryot","Prokaryot","Mezokariot","Virusoid","B","yadrosiz","medium"),
        ("Eukariot hujayra=?","Yadrosiz","Yadroli","Devorsiz","Membranasiz","B","yadroli hujayra","easy"),
        ("Lizosoma funksiyasi:","Energiya","Hazm qilish","Sintez","Harakat","B","fermentlar bor","medium"),
        ("Golji apparati funksiyasi:","Energiya","Saqlash va transport","DNK","Fotosintez","B","sekret bezlari","hard"),
        ("Endoplazmatik to'r funksiyasi:","Energiya","Transport va sintez","Ferment","Fotosintez","B","ER funksiyasi","hard"),
        ("Vakuol funksiyasi (o'simlikda):","Energiya","Suv va oziq saqlash","DNK","Ferment","B","turgor bosimi","medium"),
        ("Ildiz nima uchun:","Fotosintez","Suv va mineral so'rish","Ko'payish","Nafas","B","ildiz funksiyasi","easy"),
        ("Bargning asosiy vazifasi:","Suv so'rish","Fotosintez","Ko'payish","Tayanch","B","fotosintez","easy"),
        ("Gul nima uchun:","Fotosintez","Ko'payish","Nafas","Suv","B","jinsiy ko'payish organi","easy"),
        ("Urug' nima uchun:","Nafas","Ko'payish va tarqalish","Fotosintez","Suv","B","urug' vazifasi","easy"),
        ("Qon tarkibi:","Plazma","Plazma+hujayra","Faqat eritrotsit","Faqat leykotsit","B","qon tarkibi","easy"),
        ("Eritrotsit funksiyasi:","Himoya","O₂ tashish","Qon to'xtatish","Ferment","B","gemoglobin bor","easy"),
        ("Leykotsit funksiyasi:","O₂ tashish","Himoya","Trombosit","Ferment","B","immunitet","easy"),
        ("Trombosit funksiyasi:","O₂ tashish","Himoya","Qon ivish","Ferment","C","qon to'xtatadi","easy"),
        ("Gemoglobin nima?","Yog'","Oqsil (Fe bor)","Uglerod","Vitamin","B","Fe saqlaydi","medium"),
        ("Reflektor yoy:","Reseptor→effektor","Reseptor→nerv→effektor→miya","Reseptor→nerv→miya→effektor","Miya→effektor","C","to'liq yoy","hard"),
        ("Neyron nima?","Qon hujayra","Nerv hujayra","Miya","Mushak","B","asab hujayra","easy"),
        ("Sinaps nima?","Hujayralar tutashuvi","Neyronlar orasidagi aloqa","Qon tomir","Mushak","B","nerv aloqasi","hard"),
        ("Gormon nima?","Ferment","Kimyoviy messenger","Vitamin","Mineral","B","endokrin tizim","medium"),
        ("Adrenalin qayerda ishlab chiqariladi?","Jigar","Buyrak usti bezi","Oshqozon","Taloq","B","stressda ajraladi","medium"),
        ("Tiroksin qayerda?","Oshqozon","Qalqonsimon bez","Me'da osti bezi","Jigar","B","metabolizmni boshqaradi","medium"),
        ("Testosteron nima?","Ayol gormoni","Erkak gormoni","Insulin","Adrenalin","B","erkak jins gormoni","medium"),
        ("Estrogen nima?","Erkak gormoni","Ayol gormoni","Insulin","Kortizol","B","ayol jins gormoni","medium"),
        ("Mendel qonunlari qaysi soha?","Ekologiya","Genetika","Sitologiya","Botanika","B","irsiyat qonunlari","medium"),
        ("Dominant gen=?","Kuchsiz gen","Kuchli (namoyon bo'luvchi)","Retsessiv","O'zgaruvchan","B","dominantlik","medium"),
        ("Retsessiv gen=?","Kuchli","Yashirin (namoyon bo'lmas)","Dominant","Mutant","B","retsessivlik","medium"),
        ("Mutatsiya nima?","Normal holat","DNK o'zgarishi","Ko'payish","Metabolizm","B","irsiy o'zgarish","medium"),
        ("Ekologiya nima?","Hujayra fani","Organizm va muhit","Genetika","Evolyutsiya","B","ekologiya ta'rifi","easy"),
        ("Biotsenoze nima?","Bir tur","Ko'p turlar birligi","Ekotizim","Biosfera","B","turlar majmuasi","hard"),
        ("Ekotizim=?","Faqat tirik organizmlar","Organizm+muhit","Faqat muhit","Faqat o'simlik","B","to'liq tizim","medium"),
        ("Fotosintezda qaysi element ajraladi?","CO₂","N₂","O₂","H₂","C","kislorod ajraladi","easy"),
        ("Nafas olishda qaysi gaz kerak?","CO₂","N₂","O₂","H₂","C","kislorod kerak","easy"),
        ("Spora nima?","Urug'","Jinsiy ko'payish hujayra","Jinsiz ko'payish hujayra","Pollenlar","C","sporalar","medium"),
        ("Fototropizm nima?","Yerga qarab o'sish","Yorug'likka qarab o'sish","Suvga qarab","Haroratga","B","yorug'lik javobga","medium"),
        ("Gravitropizm nima?","Yorug'likka","Yerga qarab o'sish","Suvga","Kimyoviy","B","gravitatsiya javob","medium"),
    ],
    'history': [
        ("O'zbekiston mustaqilligi:","1990","1991","1992","1993","B","1991-yil 1-sentabr","easy"),
        ("Amir Temur tug'ilgan yil:","1336","1370","1405","1300","A","1336, Shahrisabz","easy"),
        ("1-jahon urushi:","1912","1913","1914","1915","C","1914-1918","easy"),
        ("2-jahon urushi boshlangan:","1938","1939","1940","1941","B","1939-yil 1-sentabr","easy"),
        ("2-jahon urushi tugagan:","1944","1945","1946","1947","B","1945-yil 2-sentabr","easy"),
        ("Birinchi kosmonaut:","Armstrong","Gagarin","Terashkova","Shepard","B","1961-yil 12-aprel","easy"),
        ("Fransuz inqilobi:","1776","1789","1800","1812","B","1789-yil 14-iyul","medium"),
        ("Amerika mustaqillik yili:","1776","1789","1800","1812","A","1776-yil 4-iyul","easy"),
        ("Ulug'bek rasadxonasi:","Buxoro","Xiva","Samarqand","Toshkent","C","Samarqand, 1428-29","easy"),
        ("Al-Xorazmiy sohasi:","Tibbiyot","Astronomiya","Matematika","Kimyo","C","algebra asoschisi","easy"),
        ("Al-Beruniy tug'ilgan joy:","Buxoro","Samarqand","Xorazm","Termiz","C","973-yil, Kath","medium"),
        ("Ibn Sino asosiy asari:","Algebra","Qonun (Tib)","Astronomiya","Falsafa","B","Qonun fit-tib","easy"),
        ("Buyuk Ipak yo'li:","Xitoydan Yevropaga","Hindistondan","Arabistondan","Rossiyadan","A","Sharqdan G'arbga","easy"),
        ("Qog'oz ixtirochi:","Arablar","Xitoylar","Hindlar","Yunonlar","B","qadimgi Xitoy","medium"),
        ("Matbaa ixtirochisi:","Edison","Gutenberg","Nobel","Watt","B","1440-yillar","medium"),
        ("Demokratiya tug'ilgan joy:","Rim","Misr","Yunoniston","Xitoy","C","Afina, 5-asr","medium"),
        ("Renessans qaerda boshlandi:","Fransiya","Italiya","Germaniya","Angliya","B","14-17-asrlar","medium"),
        ("Temuriylar poytaxti:","Buxoro","Xiva","Samarqand","Toshkent","C","Amir Temur davrida","easy"),
        ("Xorazm shahri qadimiy nomi:","Urganch","Kath","Xiva","Ko'hna Urganch","B","Al-Beruniy shahri","hard"),
        ("Chingizxon tug'ilgan yil:","1155","1162","1170","1180","B","taxminan 1162","hard"),
        ("Mo'g'ul imperiyasi poytaxti:","Pekin","Samarqand","Qoraqorum","Buxoro","C","Qoraqorum","hard"),
        ("Vizantiya imperiyasi qachon qulaganb:","1353","1453","1553","1400","B","1453-yil","hard"),
        ("Birinchi bosma kitob (Gutenberg):","Injil","Qur'on","Aristotel","Gomer","A","Gutenberg Injili","hard"),
        ("Kompas kim ixtiro qildi:","Arablar","Xitoylar","Hindlar","Yunonlar","B","Xitoy ixtirosi","medium"),
        ("Barut kim ixtiro qildi:","Arablar","Xitoylar","Hindlar","Rimliklar","B","Xitoy ixtirosi","medium"),
        ("Suez kanali ochilgan yil:","1849","1859","1869","1879","C","1869-yil","hard"),
        ("Panama kanali ochilgan:","1904","1914","1924","1934","B","1914-yil","hard"),
        ("Birinchi Olimpiya o'yinlari (yangi):","1892","1894","1896","1900","C","1896, Afina","medium"),
        ("BMT tashkil topdi:","1944","1945","1946","1947","B","1945-yil 24-oktabr","medium"),
        ("Sovuq urush qachon tugadi:","1989","1990","1991","1992","C","SSSR parchalanishi","medium"),
        ("Berlin devori qurildi:","1959","1961","1963","1965","B","1961-yil","medium"),
        ("Berlin devori buzildi:","1987","1988","1989","1990","C","1989-yil 9-noyabr","medium"),
        ("Birinchi yadro bomba ishlatilgan:","1944","1945","1946","1947","B","Xirosima 1945","medium"),
        ("Apollo 11 Oyga qo'ndi:","1967","1968","1969","1970","C","1969-yil 20-iyul","medium"),
        ("Internet qachon ixtiro:","1969","1979","1989","1999","A","ARPANET 1969","hard"),
        ("Birinchi mobil telefon:","1963","1973","1983","1993","B","Motorola 1973","hard"),
        ("Google tashkil topdi:","1996","1997","1998","1999","C","1998-yil","medium"),
        ("Facebook tashkil topdi:","2002","2003","2004","2005","C","2004-yil Zuckerberg","easy"),
        ("Sovet Ittifoqi parchalandi:","1989","1990","1991","1992","C","1991-yil 25-dekabr","easy"),
        ("O'zbekiston birinchi prezidenti:","Mirziyoyev","Karimov","Nishonov","Rahimov","B","Islom Karimov","easy"),
        ("Shavkat Mirziyoyev prezident:","2014","2015","2016","2017","C","2016-yil sentabr","easy"),
        ("O'zbekiston Konstitutsiyasi:","1991","1992","1993","1994","B","1992-yil 8-dekabr","medium"),
        ("Toshkent poytaxt bo'lgan:","1920","1930","1930","1924","D","1924-yil sovet davrida","hard"),
        ("Samarqand eng buyuk davri:","13-asr","14-15-asr","16-asr","17-asr","B","Temuriylar davri","medium"),
        ("Buxoro amirligini kimlar zabt etdi:","Ruslar","Mo'g'ullar","Forslar","Arablar","A","1920-yil rus qo'shini","medium"),
        ("Xiva xonligi qachon tashkil topdi:","1511","1511","1598","1700","C","16-asr oxiri","hard"),
        ("Kokand xonligi qachon:","1700","1709","1750","1800","B","1709-yil","hard"),
        ("O'zbekistonda temir yo'l qachon:","1888","1898","1906","1918","A","1888-yil Kaspiy orttidan","hard"),
        ("Toshkent zilzilasi:","1962","1966","1970","1976","B","1966-yil 26-aprel","medium"),
        ("O'zbekiston MDH ga kirdi:","1991","1992","1993","1994","A","1991-yil dekabr","medium"),
        ("Navro'z nima?","Yangi yil (21-mart)","Mustaqillik","Qurbon","Ro'za hayit","A","bahor bayram","easy"),
    ],
    'it': [
        ("HTML=?","Dasturlash tili","Belgilash tili","DB","OS","B","HyperText Markup","easy"),
        ("CSS=?","Dasturlash tili","Uslub tili","DB","Protokol","B","Cascading Style Sheets","easy"),
        ("JavaScript=?","Belgilash","Uslub","Dasturlash tili","DB","C","veb dasturlash","easy"),
        ("Python turi:","Kompilyatsiya","Interpretatsiya","Assembler","Mashina","B","interpreted","easy"),
        ("CPU=?","Xotira","Grafik","Markaziy protsessor","Tarmoq","C","Central Processing Unit","easy"),
        ("RAM=?","Doimiy xotira","Operativ xotira","Grafik","Tarmoq","B","Random Access Memory","easy"),
        ("ROM=?","Operativ xotira","Doimiy xotira","Grafik","Protsessor","B","Read Only Memory","easy"),
        ("1 GB=?","1000 MB","1024 MB","512 MB","2048 MB","B","ikkilik sistema","easy"),
        ("1010₂=?","8","10","12","14","B","1×8+0+1×2+0=10","easy"),
        ("SQL=?","Veb-dizayn","DB tili","Tarmoq","Grafika","B","Structured Query Language","easy"),
        ("HTTP=?","Fayl tizimi","Veb protokol","Dasturlash","Xavfsizlik","B","HyperText Transfer Protocol","easy"),
        ("HTTPS da S=?","Speed","Secure","Server","System","B","xavfsiz HTTP","easy"),
        ("IP manzil=?","Qurilma nomi","Tarmoq manzil","Parol","Fayl","B","Internet Protocol","easy"),
        ("DNS=?","Dastur","Domen nom tizimi","DB","Xavfsizlik","B","Domain Name System","easy"),
        ("OOP=?","Open Protocol","Ob'ektga yo'naltirilgan","Output","Online","B","Object-Oriented Programming","easy"),
        ("Git=?","Dasturlash tili","Versiya boshqaruvi","Veb server","DB","B","version control","easy"),
        ("API=?","Dastur interfeysi","Dasturlar aloqa","Veb-sayt","DB","B","Application Programming Interface","medium"),
        ("Firewall=?","Zaxira","Tarmoq xavfsizlik","Protsessor","Monitor","B","tarmoq filtri","medium"),
        ("VPN=?","Virtual Private Network","Very Personal Network","Video Protocol","Visual Panel","A","xavfsiz aloqa","medium"),
        ("Cloud computing=?","Bulutli quvvat","Masofaviy server","Lokal server","Faqat xotira","B","masofaviy hisoblash","medium"),
        ("Bug nima?","Xato","Yangi imkoniyat","Optimallashtirish","Test","A","dastur xatosi","easy"),
        ("Debugging=?","Xato qo'shish","Xatoni topish va tuzatish","Test qilish","Optimallashtirish","B","xato tuzatish","easy"),
        ("Algorithm=?","Dastur tili","Muammo yechish qadamlari","DB","Tarmoq","B","aniq qadamlar to'plami","easy"),
        ("Recursion=?","Tsikl","O'zini chaqirish","Shart","O'zgaruvchi","B","funksiya o'zini chaqiradi","medium"),
        ("Array=?","Bitta o'zgaruvchi","Bir xil turdagi elementlar","Funksiya","Sinf","B","massiv","easy"),
        ("Stack=?","FIFO","LIFO","Random","Sorted","B","Last In First Out","medium"),
        ("Queue=?","LIFO","FIFO","Random","Sorted","B","First In First Out","medium"),
        ("Binary search=?","O'rta elementni tekshirish","Birin-ketin tekshirish","Random","Sort","A","ikkilik qidirish","medium"),
        ("O(n) nima?","Xotira","Vaqt murakkabligi","Xavfsizlik","Tezlik","B","Big O notation","hard"),
        ("Inheritance OOP da=?","Abstraksiya","Meros olish","Polimorfizm","Inkapsulatsiya","B","class inheritance","medium"),
        ("Encapsulation=?","Meros","Ma'lumot yashirish","Ko'p shakllilik","Abstraksiya","B","ma'lumotni himoya","medium"),
        ("Polymorphism=?","Meros","Yashirish","Ko'p shakllilik","Abstraksiya","C","bir nom ko'p holat","medium"),
        ("Abstraction=?","Meros","Yashirish","Ko'p shakllilik","Muhim ma'lumotni ajratish","D","abstraksiya","medium"),
        ("MVC=?","Model-View-Control","Model-View-Controller","Main-View-Class","Multi-Version","B","arxitektura pattern","hard"),
        ("REST API=?","Protokol","Arxitektura uslubi","Dasturlash tili","DB","B","web service uslubi","hard"),
        ("JSON=?","Java Object","JavaScript Object Notation","Just Simple Object","Java System","B","ma'lumot formati","medium"),
        ("XML=?","Extra Markup","eXtensible Markup Language","X Markup","Extra Meta","B","ma'lumot formati","medium"),
        ("Docker=?","Dasturlash tili","Konteynerizatsiya","DB","Versiya boshqaruvi","B","container platform","hard"),
        ("Kubernetes=?","Dasturlash","Konteyner orkestrasiya","DB","Monitor","B","container management","hard"),
        ("Machine Learning=?","Dasturlash","Ma'lumotdan o'rganish","DB","Tarmoq","B","sun'iy intellekt turi","hard"),
        ("Neural network=?","Tarmoq","Miya modelidagi AI","DB","Protokol","B","chuqur o'rganish","hard"),
        ("Blockchain=?","Bank tizimi","Zanjirli tarqatilgan daftar","Veb server","Protokol","B","kriptovalyuta asosi","hard"),
        ("Agile metodologiya=?","Qattiq reja","Iterativ yondashuv","Shallof test","Faqat hujjat","B","moslashuvchan ishlab chiqish","hard"),
        ("Scrum=?","Dasturlash tili","Agile framework","DB","Test uslubi","B","sprint asosida ishlash","hard"),
        ("CI/CD=?","Code Integration","Continuous Integration/Deployment","Client-Interface","Copy-Install","B","avtomatlashtirilgan jarayon","hard"),
        ("Linux kernel yaratdi:","Bill Gates","Linus Torvalds","Steve Jobs","Mark Zuckerberg","B","1991-yil","medium"),
        ("Python yaratdi:","Dennis Ritchie","Guido van Rossum","James Gosling","Bjarne Stroustrup","B","1991-yil","medium"),
        ("Java yaratdi:","Bill Gates","Guido van Rossum","James Gosling","Bjarne Stroustrup","C","Sun Microsystems","medium"),
        ("C++ yaratdi:","Dennis Ritchie","Guido van Rossum","James Gosling","Bjarne Stroustrup","D","1985-yil","hard"),
        ("www ixtirochisi:","Bill Gates","Tim Berners-Lee","Steve Jobs","Linus Torvalds","B","1989-yil CERN","medium"),
    ],
}

total = 0
for code, questions in ALL_QUESTIONS.items():
    try:
        subj = Subject.objects.get(code=code)
    except Subject.DoesNotExist:
        print(f"  ⚠️ Subject '{code}' topilmadi")
        continue
    added = 0
    for q in questions:
        text, a, b, c, d, ans, exp, diff = q
        if not Question.objects.filter(subject=subj, text_uz=text).exists():
            Question.objects.create(
                subject=subj, text_uz=text,
                option_a=a, option_b=b, option_c=c, option_d=d,
                correct_answer=ans, explanation_uz=exp,
                difficulty=diff, is_active=True, xp_reward=10,
            )
            added += 1
    count = Question.objects.filter(subject=subj, is_active=True).count()
    print(f"  ✅ {subj.name_uz}: +{added} yangi → jami {count} ta savol")
    total += added

print(f"\n✅ Jami {total} ta yangi savol qo'shildi!")
