# Generated by Django 5.0.4 on 2026-05-16 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aichat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aichat'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aichat',
            index=models.Index(fields=['user', 'is_saved'], name='ai_chats_user_id_ea5493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiusagelog',
            unique_together={('user', 'date')},
        ),
    ]
